# Generated by Django 3.0.5 on 2020-06-10 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
