# Generated by Django 3.0.5 on 2020-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_recommendation_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation',
            field=models.CharField(max_length=1500),
        ),
    ]
