# Generated by Django 3.0.5 on 2020-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_auto_20200610_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recommendations/%Y/%m/'),
        ),
    ]
