# Generated by Django 3.0.5 on 2020-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_recommendation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='recommendations/%Y/%m/'),
        ),
    ]
