# Generated by Django 3.0.5 on 2020-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_auto_20200610_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='works/')),
                ('date_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
