# Generated by Django 3.0.5 on 2020-06-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
