# Generated by Django 3.0.5 on 2020-06-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_auto_20200610_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
