# Generated by Django 3.0.5 on 2020-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'slug')},
        ),
    ]
