# Generated by Django 3.0.5 on 2020-06-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0016_auto_20200611_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='works/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='recommendations/%Y/%m/'),
        ),
    ]
