# Generated by Django 3.0.5 on 2020-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0017_auto_20200611_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
